# Generated by Django 3.1.7 on 2021-03-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('ephemeris', models.CharField(max_length=30)),
                ('time', models.TimeField()),
                ('description', models.TextField()),
            ],
        ),
    ]
