# Generated by Django 3.1.7 on 2021-03-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('upc', 'upcoming'), ('fin', 'finished')], default='upc', max_length=40, null=True),
        ),
    ]
