# Generated by Django 3.1.7 on 2021-03-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20210322_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='phone',
            field=models.CharField(default=18646405680, max_length=11),
            preserve_default=False,
        ),
    ]
