# Generated by Django 3.1.7 on 2021-03-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
