# Generated by Django 3.1.7 on 2021-03-28 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_remove_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_of_event',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
