# Generated by Django 3.1.7 on 2021-03-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_event_date_of_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='occurrences',
        ),
        migrations.RemoveField(
            model_name='event',
            name='status',
        ),
        migrations.AddField(
            model_name='event',
            name='solar_event',
            field=models.BooleanField(default=False),
        ),
    ]
