# Generated by Django 3.1.7 on 2021-03-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210320_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default=-7183, max_length=11),
            preserve_default=False,
        ),
    ]
