# Generated by Django 3.1.7 on 2021-03-23 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210323_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, default='Greenville', max_length=50, null=True),
        ),
    ]
