# Generated by Django 3.1.7 on 2021-03-29 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_event_date_of_event'),
        ('ephemeris', '0006_auto_20210326_2015'),
        ('accounts', '0010_auto_20210329_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ephemeris_notifications',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ephemeris.ephem'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_event_notifications',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
    ]
