# Generated by Django 3.1.7 on 2021-03-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ephemeris', '0006_auto_20210326_2015'),
        ('events', '0014_event_date_of_event'),
        ('accounts', '0011_auto_20210329_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ephemeris_notifications',
        ),
        migrations.AddField(
            model_name='profile',
            name='ephemeris_notifications',
            field=models.ManyToManyField(blank=True, null=True, to='ephemeris.Ephem'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_event_notifications',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_event_notifications',
            field=models.ManyToManyField(blank=True, null=True, to='events.Event'),
        ),
    ]
