# Generated by Django 3.1.7 on 2021-03-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ephemeris', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ephem',
            name='alt',
        ),
        migrations.RemoveField(
            model_name='ephem',
            name='az',
        ),
        migrations.AddField(
            model_name='ephem',
            name='rise_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ephem',
            name='set_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
