# Generated by Django 3.1.7 on 2021-03-18 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ephemeris', '0002_auto_20210315_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ephem',
            name='image',
            field=models.ImageField(upload_to='ephemeris/'),
        ),
    ]
