# Generated by Django 3.1.7 on 2021-03-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ephemeris', '0003_auto_20210318_0234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
