# Generated by Django 3.1.7 on 2021-03-26 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ephemeris', '0004_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ephem',
            name='rise_time',
        ),
        migrations.RemoveField(
            model_name='ephem',
            name='set_time',
        ),
    ]
