# Generated by Django 3.1.7 on 2021-03-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ephemeris', '0005_auto_20210326_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='ephem',
            name='rise_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ephem',
            name='set_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
