# Generated by Django 3.1.7 on 2021-03-29 15:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ephemeris', '0006_auto_20210326_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='ephem',
            name='subscribers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
