# Generated by Django 3.1.7 on 2021-03-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ephemeris', '0007_ephem_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ephem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ephemeris/'),
        ),
        migrations.AlterField(
            model_name='ephem',
            name='magnitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ephem',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
