# Generated by Django 3.1.7 on 2021-03-29 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ephemeris', '0008_auto_20210329_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='name',
        ),
    ]
