# Generated by Django 3.1.7 on 2021-03-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ephemeris', '0009_remove_test_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ephem',
            name='ephem_type',
            field=models.CharField(choices=[('celestial_bodies', 'celestial_bodies'), ('solar_events', 'solar_events')], default='celestial_bodies', max_length=26),
        ),
    ]
