# Generated by Django 3.1.7 on 2021-03-29 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ephemeris', '0011_auto_20210329_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ephem',
            name='ephem_type',
        ),
    ]
